### ISSUE TITLE
3.0.0 release todo

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3731]
Issue updated since https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212530813:
This will not be 2.4 but 3.0. See reasons:

* `dev-master` has already several BC breaking modifications that was merged (sigh)
* Pushing a major release would prevent other stable sonata bundle to auto-update to the new version and might be failed
* This will be the occasion to make a **real** separation between the old and the new versions management

Since this time, if you're requiring sonata-project/admin-bundle `2.4.*@dev` on `composer.json`, you have to change to `3.*@dev`, `3.x-dev@dev` or `dev-master@dev`.
This is the only breaking change.

For possible dependencies issues, see https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212636270.

#### **PLEASE DO NOT POST YOUR DEPENDENCIES ISSUES HERE**
This issue is not here for that. If you tried previous solutions and are still stuck, please open **another issue** on the **concerned project**.

Even if it's a new major, no BC breaking Pull Request will be merge until 3.0.0 release.
The reason is simple: Lot of user are already using `dev-master` version of sonata-admin and we didn't tag minor/major releases from a long time. Let's do it painless.

This issue goal is to list all to do things that we **must** do before and after tag this version.

To many changes between 2.3 and master branch, we have to take precaution.

This issue will be a model for another repository minor tag before start the new [release process management](https://github.com/sonata-project/SonataAdminBundle/issues/3053).

### Internal changes

- [x] Change `2.4.x-dev` to `3.x-dev` on `composer.json` (#3732)
- [x] Change deprecation comment and warning from 3.0 to 4.0 and 2.4 to 3.0. (Thanks @greg0ire for remember) (#3733)
- [ ] Change / reset milestones

### Internal dependencies issues

List etablished from `composer show --all sonata-project/*`.
Not all packages need to be updated.

* [sonata-project/admin-bundle](https://packagist.org/packages/sonata-project/admin-bundle)
(will be **3.x**): 
  - [x] https://github.com/sonata-project/SonataAdminBundle/pull/3751
* [sonata-project/admin-search-bundle](https://packagist.org/packages/sonata-project/admin-search-bundle)
(will be **?**):
* [sonata-project/block-bundle](https://packagist.org/packages/sonata-project/block-bundle)
(will be **3.x**): 
  - [x] https://github.com/sonata-project/SonataBlockBundle/pull/259
* [sonata-project/cache](https://packagist.org/packages/sonata-project/cache)
(will be **?**):
* [sonata-project/cache-bundle](https://packagist.org/packages/sonata-project/cache-bundle)
(will be **?**):
* [sonata-project/classification-bundle](https://packagist.org/packages/sonata-project/classification-bundle)
(will be **3.x**):
  - [x] https://github.com/sonata-project/SonataClassificationBundle/pull/183
  - [x] https://github.com/sonata-project/SonataClassificationBundle/pull/184
  - [x] https://github.com/sonata-project/SonataClassificationBundle/pull/189
  - [x] https://github.com/sonata-project/SonataClassificationBundle/pull/190
* [sonata-project/comment-bundle](https://packagist.org/packages/sonata-project/comment-bundle)
(will be **?**):
* [sonata-project/composer-archive-creator](https://packagist.org/packages/sonata-project/composer-archive-creator)
(will be **?**):
* [sonata-project/core-bundle](https://packagist.org/packages/sonata-project/core-bundle)
(will be **3.x**): 
  - [x] https://github.com/sonata-project/SonataCoreBundle/pull/240
* [sonata-project/dashboard-bundle](https://packagist.org/packages/sonata-project/dashboard-bundle)
(will be **?**):
* [sonata-project/datagrid-bundle](https://packagist.org/packages/sonata-project/datagrid-bundle)
(will be **?**):
* [sonata-project/doctrine-extensions](https://packagist.org/packages/sonata-project/doctrine-extensions)
(will be **?**):
* [sonata-project/doctrine-mongodb-admin-bundle](https://packagist.org/packages/sonata-project/doctrine-mongodb-admin-bundle)
(will be **3.x**):
  - [ ] https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/162
* [sonata-project/doctrine-orm-admin-bundle](https://packagist.org/packages/sonata-project/doctrine-orm-admin-bundle)
(will be **3.x**):
  - [x] https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/534
  - [x] https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/538
* [sonata-project/doctrine-phpcr-admin-bundle](https://packagist.org/packages/sonata-project/doctrine-phpcr-admin-bundle) (will be **2.x**):
  - [x] https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/370
  - [x] https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/371
  - [ ] https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/373
* [sonata-project/easy-extends-bundle](https://packagist.org/packages/sonata-project/easy-extends-bundle)
(will be **2.x**):
  - [x] https://github.com/sonata-project/SonataEasyExtendsBundle/pull/73
* [sonata-project/ecommerce](https://packagist.org/packages/sonata-project/ecommerce)
(will be **?**):
* [sonata-project/exporter](https://packagist.org/packages/sonata-project/exporter)
(will be **1.x**):
 - [x] https://github.com/sonata-project/exporter/pull/61
* [sonata-project/formatter-bundle](https://packagist.org/packages/sonata-project/formatter-bundle)
(will be **3.x**): 
  - [x] https://github.com/sonata-project/SonataFormatterBundle/pull/155
* [sonata-project/google-authenticator](https://packagist.org/packages/sonata-project/google-authenticator)
(will be **?**):
* [sonata-project/intl-bundle](https://packagist.org/packages/sonata-project/intl-bundle)
(will be **?**):
* [sonata-project/markitup-bundle](https://packagist.org/packages/sonata-project/markitup-bundle)
(will be **?**):
* [sonata-project/media-bundle](https://packagist.org/packages/sonata-project/media-bundle)
(will be **3.x**):
  - [x] https://github.com/sonata-project/SonataMediaBundle/pull/990
  - [x] https://github.com/sonata-project/SonataMediaBundle/pull/494
* [sonata-project/news-bundle](https://packagist.org/packages/sonata-project/news-bundle)
(will be **?**):
* [sonata-project/notification-bundle](https://packagist.org/packages/sonata-project/notification-bundle)
(will be **3.x**):
  - [x] https://github.com/sonata-project/SonataNotificationBundle/pull/169
* [sonata-project/page-bundle](https://packagist.org/packages/sonata-project/page-bundle)
(will be **3.x**):
  - [x] https://github.com/sonata-project/SonataPageBundle/pull/634
  - [x] https://github.com/sonata-project/SonataPageBundle/pull/637
* [sonata-project/propel-admin-bundle](https://packagist.org/packages/sonata-project/propel-admin-bundle)
(will be **?**):
* [sonata-project/sandbox](https://packagist.org/packages/sonata-project/sandbox)
(will be **?**):
* [sonata-project/seo-bundle](https://packagist.org/packages/sonata-project/seo-bundle)
(will be **2.x**):
 - [x] https://github.com/sonata-project/SonataSeoBundle/pull/124
* [sonata-project/sonata-composer](https://packagist.org/packages/sonata-project/sonata-composer)
(will be **?**):
* [sonata-project/timeline-bundle](https://packagist.org/packages/sonata-project/timeline-bundle)
(will be **?**):
* [sonata-project/translation-bundle](https://packagist.org/packages/sonata-project/translation-bundle)
(will be **2.x**):
  - [ ] https://github.com/sonata-project/SonataTranslationBundle/pull/94
* [sonata-project/user-bundle](https://packagist.org/packages/sonata-project/user-bundle)
(will be **?**):

## Tagging

- [x] Tag the `v3.0.0` release. Rofl.

### Related bundles stable releases

- [ ]

### Misc

- [x] Remove `2.0` -> `2.2` branches
- [x] Move `2.3` to `2.x` branch (just for history, no modification will be allowed).
- [x] Create a `3.x` branch => For minor releases
- [x] Closes all PR concerning patch or minor modification with a message to tell user to rebase it on `3.x`
- [x] Do a "We are very glad that finally happenned!" tweet. :tada: 

Am I missing something? Tell me! :+1: 

## Tagged project

* core-bundle: [3.0.0](https://github.com/sonata-project/SonataCoreBundle/releases/tag/3.0.0)
* block-bundle: [3.0.0](https://github.com/sonata-project/SonataBlockBundle/releases/tag/3.0.0)
* admin-bundle: [3.0.0](https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.0.0)
* user-bundle: [3.0.0](https://github.com/sonata-project/SonataUserBundle/releases/tag/3.0.0)
* formatter-bundle: [3.0.0](https://github.com/sonata-project/SonataFormatterBundle/releases/tag/3.0.0)
* seo-bundle: [2.0.2](https://github.com/sonata-project/SonataSeoBundle/releases/tag/2.0.2)
* classification-bundle: [3.0.0](https://github.com/sonata-project/SonataClassificationBundle/releases/tag/3.0.0)
* media-bundle: [3.0.0](https://github.com/sonata-project/SonataMediaBundle/releases/tag/3.0.0)
* comment-bundle: [3.0.0](https://github.com/sonata-project/SonataCommentBundle/releases/tag/3.0.0)
* page-bundle: [3.0.0](https://github.com/sonata-project/SonataPageBundle/releases/tag/3.0.0)
* news-bundle: [3.0.0](https://github.com/sonata-project/SonataNewsBundle/releases/tag/3.0.0)

**Comment by Koc** [comment]
Would be great merge pending PR first https://github.com/sonata-project/SonataAdminBundle/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.4

**Comment by OskarStark** [comment]
ping @mvhirsch

**Comment by javiereguiluz** [comment]
@Soullivaneuh what about signing the new `v2.4.0` tag? [Reference](https://github.com/blog/2144-gpg-signature-verification)

**Comment by javiereguiluz** [comment]
@Soullivaneuh another suggestion: prepare a human-friendly changelog of the main features and bug fixes introduced by the new version.

**Comment by mvhirsch** [comment]
What about updating the documentation for 2.4?

**Comment by ju1ius** [comment]
> Closes all PR concerning patch or minor modification with a message to tell user to rebase it on 2.x

@Soullivaneuh  I would say do not close right away. Label the issue as outdated, send a message to author telling to rebase and that the issue will be closed in a given time frame if they don't.

People tend to get mad when their PR/tickets receive no response for months, then is abruptly closed because the version changes.

**Comment by ju1ius** [comment]
@Koc I would say :-1: for merging #3258 in 2.4

The idea is great but there's a big responsiveness problem with the current top nav layout that can't be fixed in a BC way.
Basically, we need to move the breadcrumb from the top bar to the main body, because a breadcrumb has by definition a potentially infinite length, and in a fixed appbar everything should fit on one line.

**Comment by Soullivaneuh** [comment]
After discussing with @rande and @sonata-project/contributors we decided to not push a minor release but a **major** one.

So it will not be 2.4.0 but **3.0.0**.

For some reasons:

* `dev-master` has already several BC breaking modifications that was merged (sigh)
* Pushing a major release would prevent other stable sonata bundle to auto-update to the new version and might be failed
* This will be the occasion to make a **real** separation between the old and the new versions management

I'll update the issue accordingly, with corresponding warns.

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh another suggestion: prepare a "curated" changelog of the main features and bug fixes introduced by the new version.

Yeah, I think we should create a new clear changelog starting from 3.0.

**Comment by Soullivaneuh** [comment]
> What about updating the documentation for 2.4?

~~2.4~~ -> 3.0

What do you mean?

**Comment by core23** [comment]
[ ] Move tickets from milestones to > 3.0 / 4.0

**Comment by Soullivaneuh** [comment]
> I would say do not close right away. Label the issue as outdated, send a message to author telling authors to rebase and that the issue will be closed in a given time frame if they don't.

@ju1ius I would see on a reverse way: people would reopen a pr if **they want** to continue.

In your way, we will have a lot of PR without continuing work but still open on the list. It's hard, but we will have a new and clean start.

ping @rande and @sonata-project/contributors for opinion.

> People tend to get angry when their PR/tickets receive no response for months, then is abruptly closed because the version changes.

We just have to explain clearly why we are doing this. Sebastian did this for PHPUnit and it works great AFAIK.

For https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212509707, this is not related to this issue. Please comment on the related PR.

**Comment by Soullivaneuh** [comment]
> [ ] Move tickets from milestones to > 3.0 / 4.0

I think we will reset the milestones at all.

**Comment by ju1ius** [comment]
> We just have to explain clearly why we are doing this. Sebastian did this for PHPUnit and it works great AFAIK.

Yes explaining is key.
I had the GNOME project in mind with their habit to automatically close every ticket just because it was submitted against an old version. More often than not the bug is still present and it leads to issues staying unresolved for years. It really pisses people off and discourage them to submit bugs and patches, which is a shame.

**Comment by Soullivaneuh** [comment]
@ju1ius I understand your point of view. I still think we should do the closing way.

This is a kind of sacrifice, but we have to cleanup to have a good see of what to do for the future.

**Comment by Avtonom** [comment]
sonata-project/admin-bundle ~2.4 -> no matching package found

**Comment by Avtonom** [comment]
@Soullivaneuh
sonata-project/admin-bundle ~2.4 -> no matching package found

**Comment by Soullivaneuh** [comment]
@Avtonom just see https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212530813 and #3732.

**Comment by Avtonom** [comment]
thanks for the tip! I not immediately caught the depth changes.
How do I fix it?
> sonata-project/classification-bundle 2.3.x-dev requires sonata-project/admin-bundle ~2.4 -> no matching package found

**Comment by Avtonom** [comment]
@Soullivaneuh, thanks for the tip! I not immediately caught the depth changes.
How do I fix it?
sonata-project/classification-bundle 2.3.x-dev requires sonata-project/admin-bundle ~2.4 -> no matching package found

**Comment by ju1ius** [comment]
@Avtonom  Have you tried something like this (untested) ?
```json
{
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/sonata-project/SonataAdminBundle.git"
    }
  ],
  "require": {
    "sonata-project/admin-bundle": "dev-master as 2.4"
  }
}
```

**Comment by Avtonom** [comment]
Thank you!
        "sonata-project/admin-bundle": "dev-master as 2.4",
        "sonata-project/doctrine-orm-admin-bundle": "2.4.x-dev",
        "sonata-project/classification-bundle": "2.3.x-dev",

**Comment by ju1ius** [comment]
@Soullivaneuh Maybe document this in the release note as a temporary solution untils all bundles switch to the new release process ?

**Comment by Soullivaneuh** [comment]
@ju1ius I updated the post.

**Comment by core23** [comment]
After creating the new 3.x branches, what will we do with the old 2.x versions? Leave them as they are or would we supply patches and security updates? 

IMO we must support them too, because the users couldn't simply use the new versions and rely on the old one.

**Comment by Soullivaneuh** [comment]
@core23 The goal is to not support legacy branch and focus to only one to reduce the maintaining difficulty.

So globally no. After that, if someone have a **very critical security** issue to fix, we can consider that. But that's all, no patches will be accepted.

As I said, lot of people are already using `dev-master` because of compatibility with recent framework / library. Just see the download stats: https://packagist.org/packages/sonata-project/admin-bundle/stats#dev-master

This is also why I prefer to not merge new BC breaking PR until 3.0.

**Comment by muspelheim** [comment]
@Soullivaneuh Hi, how much time need for migrate to 3.0 and stabilization?

**Comment by Soullivaneuh** [comment]
@muspelheim We hope to get a stable release of each bundle at beginning of may 2016.

**Comment by boltunoreh** [comment]
> Since this time, if you're requiring sonata-project/admin-bundle 2.4.*@dev on composer.json, you have to change to 3.0.*@dev of dev-master@dev.

i think it should be 3.*@dev not 3.0.*@dev, right?

**Comment by Soullivaneuh** [comment]
@boltunoreh indeed! Corrected, thanks!

**Comment by muspelheim** [comment]
@Soullivaneuh How I can help in this?

**Comment by acrozes** [comment]
For Internal dependencies issues:
Maybe add: sonata-project/SonataDoctrineMongoDBAdminBundle

Presently: sonata-project/doctrine-mongodb-admin-bundle dev-master requires sonata-project/admin-bundle ~2.3

**Comment by jmontoyaa** [comment]
Dependency issue with pagebundle:

```
Problem 1
    - sonata-project/page-bundle dev-master requires sonata-project/admin-bundle ~2.4 -> satisfiable by sonata-project/admin-bundle[2.4.x-dev].
    - sonata-project/page-bundle dev-master requires sonata-project/admin-bundle ~2.4 -> satisfiable by sonata-project/admin-bundle[2.4.x-dev].
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 2.4.x-dev].
    - Installation request for sonata-project/admin-bundle 3.x-dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Installation request for sonata-project/page-bundle dev-master -> satisfiable by sonata-project/page-bundle[dev-master].

```

**Comment by jmontoyaa** [comment]
Maybe it will be a good a day to make sandbox based in 3.x

**Comment by Soullivaneuh** [comment]
Please don't post your dependencies issue here.

See: https://github.com/sonata-project/SonataAdminBundle/issues/3731#issuecomment-212636270

If you don't success to fix it, please open an issue on the concerned project.

> Maybe it will be a good a day to make sandbox based in 3.x

It's planned.

**Comment by webdevilopers** [comment]
Currently Composer update fails:

```json
        "friendsofsymfony/user-bundle": "1.3.*",
        "sonata-project/core-bundle": "dev-master",
        "sonata-project/admin-bundle": "3.*@dev",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/cache-bundle": "dev-master",
        "sonata-project/datagrid-bundle": "dev-master",
        "sonata-project/user-bundle": "dev-master",
        "sonata-project/intl-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "dev-master",
        "sonata-project/doctrine-mongodb-admin-bundle": "dev-master",
        "sonata-project/translation-bundle": "dev-master",
```

```
    - sonata-project/translation-bundle dev-master requires sonata-project/admin-bundle ^2.3.0|~2.4@dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev, 2.3.x-dev].
    - sonata-project/translation-bundle dev-master requires sonata-project/admin-bundle ^2.3.0|~2.4@dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev, 2.3.x-dev].
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 2.4.x-dev].
    - Can only install one of: sonata-project/admin-bundle[3.x-dev, 2.3.x-dev].
    - Installation request for sonata-project/admin-bundle 3.*@dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Installation request for sonata-project/translation-bundle dev-master -> satisfiable by sonata-project/translation-bundle[dev-master].
```

Other versions I tested fail with "sonata-project/doctrine-orm-admin-bundle". What is the current recommended setup?

**Comment by Soullivaneuh** [comment]
@webdevilopers please read #3731 (comment). You have to use dependency aliases for now.

Please again, open issues on dedicated projects if you're still failing.

All other dependency issues messages posted here will be deleted.

**Comment by greg0ire** [comment]
> What is the current recommended setup?

The current recommended setup is and always will be : stable branches.

**Comment by webdevilopers** [comment]
Totally agree @greg0ire but there were some issues in *2.3* that I think havn't been fixed and my Customer demands it. Anyway, I tried the settings of the comment @Soullivaneuh linked:

```json
        "sonata-project/core-bundle": "dev-master",
        "sonata-project/admin-bundle": "dev-master as 2.4",
        "sonata-project/doctrine-orm-admin-bundle": "2.4.x-dev",
        "sonata-project/classification-bundle": "2.3.x-dev",
        "sonata-project/cache-bundle": "dev-master",
        "sonata-project/datagrid-bundle": "dev-master",
        "sonata-project/user-bundle": "dev-master",
        "sonata-project/intl-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "dev-master",
        "sonata-project/doctrine-mongodb-admin-bundle": "dev-master",
        "sonata-project/translation-bundle": "dev-master",
```

But again it fails:
```
  Problem 1
    - The requested package sonata-project/doctrine-orm-admin-bundle could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package sonata-project/classification-bundle could not be found in any version, there may be a typo in the package name.
  Problem 3
    - Can only install one of: sonata-project/core-bundle[2.x-dev, dev-master].
    - Can only install one of: sonata-project/core-bundle[dev-master, 2.x-dev].
    - sonata-project/admin-bundle dev-master requires sonata-project/core-bundle ^2.3.10 -> satisfiable by sonata-project/core-bundle[2.x-dev].
    - Installation request for sonata-project/admin-bundle dev-master as 2.4 -> satisfiable by sonata-project/admin-bundle[dev-master].
    - Installation request for sonata-project/core-bundle dev-master -> satisfiable by sonata-project/core-bundle[dev-master].
```

Is there any other open issue to post these dependecy problems? Sorry for posting this once again.

**Comment by greg0ire** [comment]
What's wrong with opening your own issue ?

**Comment by greg0ire** [comment]
Open your issue on the orm bundle issue tracker.

**Comment by ju1ius** [comment]
@webdevilopers Have you tried tweaking the version alias ?
If you use `doctrine-orm-admin-bundle@dev-master`, I think it should be
```json
"require": {
  "sonata-project/admin-bundle": "dev-master as 2.4.x-dev"
}
```
or sthg like that

**Comment by jayesbe** [comment]
If anyone needs some insight into their own depedencies.. I just resolved mine with

```
		"sonata-project/admin-bundle" : "3.x-dev as 2.4",
		"sonata-project/doctrine-orm-admin-bundle" : "3.x-dev as 2.4",
		"sonata-project/user-bundle" : "^2.2",
		"sonata-project/media-bundle" : "2.4.x-dev",
		"sonata-project/classification-bundle" : "dev-master as 2.3",
		"sonata-project/datagrid-bundle" : "dev-master",
```

For the moment ;)

**Comment by pulzarraider** [comment]
> Remove 2.0 -> 2.2 branches
@Soullivaneuh this can't be done. It will cause to break projects that use the old Sonata version and we will probably lose something of the history.

**Comment by Lo-X** [comment]
@jayesbe depedency fix above doesn't work for me : 

```
    - sonata-project/admin-bundle 3.x-dev conflicts with jms/di-extra-bundle[1.5.0].
    - sonata-project/admin-bundle 3.x-dev conflicts with jms/di-extra-bundle[1.5.0].
    - Installation request for sonata-project/admin-bundle 3.x-dev as 2.4 -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Installation request for jms/di-extra-bundle 1.5.0 -> satisfiable by jms/di-extra-bundle[1.5.0].
```

Why didn't you add a 2.4 tag before breaking it into 3.x ? Would have been smoother

**Comment by greg0ire** [comment]
Reminder : **PLEASE DO NOT POST YOUR DEPENDENCIES ISSUES HERE**

**Comment by Soullivaneuh** [comment]
@pulzarraider why? 2.0 -> 2.2 branches has stable releases and those branches must not be maintained anymore.

**Comment by pulzarraider** [comment]
Branch `2.0` has no `2.0.*` tag. We should release at least `2.0.0`.

Branches `2.1` and `2.2` has some commits, that wasn't tagged yet after the latest release.
New versions `2.1.1`, `2.2.13` should be released.

After this we should inform all users, that using the branch alias (e.g. "dev-2.2 as 2.2.x-dev") probably won't work and they should use just the stable releases, e.g. `~2.2` for projects using old Sonata.

**Comment by Soullivaneuh** [comment]
> Branch `2.0` has no `2.0.*` tag. We should release at least `2.0.0`.

> Branches `2.1` and `2.2` has some commits, that wasn't tagged yet after the latest release.
> New versions `2.1.1`, `2.2.13` should be released.

Yeah in this case I will add releases. It's weirs that this was not done before.

> After this we should inform all users, that using the branch alias (e.g. "dev-2.2 as 2.2.x-dev") probably won't work and they should use just the stable releases, e.g. `~2.2` for projects using old Sonata.

The issue is right here for this. And using `2.2.x-dev` **is** using a unstable branch, so breaking things can coming. The developer should know about that. ;-)

**Comment by samuel4x4** [comment]
Hi @jayesbe, can you please show me your full composer.json file? What version of Symfony do you have? Thanks!

**Comment by jayesbe** [comment]
Great question. Should have mentioned. Im using Symfony 2.7

These are my defaults

                "symfony/symfony" : "2.7.*",
                "doctrine/orm" : "~2.2,>=2.2.3,<2.5",
                "doctrine/dbal" : "<2.5",
                "doctrine/doctrine-bundle" : "~1.4",
                "twig/extensions" : "~1.0",

Its possible you have dependencies I do not which require different
versions of sonata bundles. If that is the case you may be forced to fork
those other dependencies and update their composer.json so it looks at the
proper sonata bundle.

**Comment by Soullivaneuh** [comment]
@pulzarraider concerning branches and tags for admin-bundle:

* `2.0`: Absolutely not tag. I think this branch is old and not really used: https://packagist.org/packages/sonata-project/admin-bundle/stats#2.0.x-dev
This can be removed.
* `2.1`: Tagged `2.1.1`: https://github.com/sonata-project/SonataAdminBundle/compare/2.1.1...2.1
* `2.2`: Tagged `2.12.13`: https://github.com/sonata-project/SonataAdminBundle/compare/2.2.13...2.2
* `2.3`: Nothing to do: https://github.com/sonata-project/SonataAdminBundle/compare/2.3.10...2.3

Right now we should **not** accept any PR on 2.0 to 2.2 anymore.

Plan for soon:

* Try merge last fixes for 2.3: https://github.com/sonata-project/SonataAdminBundle/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3A2.3
* Create a 2.x branch and push new tag for 2.3
* Remove old branches
* Tag a first alpha for 3.0

After that, 2.x branch should be for bugfixes only and master for no BC breaking features.

After 3.0 stable, a `3.x` branch will be created. So we will get:

* `3.x` for BC features and bugfix.
* `master` (4.x) for BC breaking feature, deprecation removal etc.

And we will start following the new organization: https://github.com/sonata-project/SonataAdminBundle/issues/3053 :tada:

**Comment by core23** [comment]
> After 3.0 stable, a 3.x branch will be created. So we will get:
>
>    3.x for BC features and bugfix.
>    master (4.x) for BC breaking feature, deprecation removal etc.

After 3.0 stable, we remove the 2.x branch? Or will we support bugfixes for 2.x and 3.x? Just to clearify your list...

**Comment by Soullivaneuh** [comment]
@core23 No I'm talking about removing `2.0`, `2.1`, `2.2` and `2.3` branches.

`2.x` will be created but just for history at the end.

The rule will always be the same, only two branch to maintain: `master` and the last stable branch (`3.x` at the end).

**Comment by tim96** [comment]
> We hope to get a stable release of each bundle at beginning of may 2016.

@Soullivaneuh do you need some help?

**Comment by Soullivaneuh** [comment]
@tim96 Not especially for this part thanks.

Actually we have a must have to validate, the changelog: https://github.com/sonata-project/dev-kit/issues/8

After that, I think major releases will be push project by project, beginning by core-bundle... :wink:

**Comment by pulzarraider** [comment]
> 2.0: Absolutely not tag. I think this branch is old and not really used: https://packagist.org/packages/sonata-project/admin-bundle/stats#2.0.x-dev This can be removed.
@Soullivaneuh yes, probably no one is using it with composer, but it should be tagged so we don't lost any commit that was merged. I think that we should tag it is as 2.0.0.

**Comment by Soullivaneuh** [comment]
@pulzarraider Every go: https://github.com/sonata-project/SonataAdminBundle/releases/tag/2.0.0

**Comment by pulzarraider** [comment]
@Soullivaneuh thank you

**Comment by Soullivaneuh** [comment]
SonataCoreBundle 3.0.0 is out!

Tagging progress will be updated at the end of the main issue message: https://github.com/sonata-project/SonataAdminBundle/issues/3731

**Comment by hoangitt** [comment]
- Hi @Soullivaneuh, I can't update version 3.0. Please help me, thanks you and sorry because skill English is not good.
- My composer:
`"sonata-project/easy-extends-bundle": "~2.1@dev",
        "sonata-project/seo-bundle": "~2.0",
        "sonata-project/doctrine-extensions": "~1@dev",
        "sonata-project/intl-bundle": "~2.2@dev",
        "sonata-project/admin-bundle": "3.x-dev",
        "sonata-project/doctrine-orm-admin-bundle": "3.x-dev",
        "sonata-project/notification-bundle": "~2.2@dev",
        "sonata-project/block-bundle": "~2.3@dev",
        "sonata-project/media-bundle": "~2.4@dev",
        "sonata-project/user-bundle": "~2.2@dev",
        "sonata-project/cache-bundle": "~2.1@dev",
        "sonata-project/cache": "~1.0@dev",
        "sonata-project/page-bundle": "~2.4@dev",
        "sonata-project/core-bundle": "2.3.x-dev",
        "sonata-project/formatter-bundle": "~2.4@dev",
        "sonata-project/news-bundle": "~2.3@dev",
        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/exporter": "~1.3@dev",
        "sonata-project/classification-bundle": "~2.2@dev",
        "sonata-project/sonata-composer": "dev-master"`

**Comment by anhnt0212** [comment]
yeah...i will try update composer :+1:

**Comment by hoangitt** [comment]
@anhnt0212 you updated composer, please help me !!!

**Comment by Soullivaneuh** [comment]
We are almost here! :tada: 

All packages are now updated except 3 of them.

I closes this one in favor of dev-kit one: https://github.com/sonata-project/dev-kit/issues/140

Thanks all for your support about this new adventure! :dancers: :smiley:
