### ISSUE TITLE
Remove inline scripts

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4031]
For many reasons, we should remove all scripts from the templates. We could replace them with data listerns like in the page bundle: https://github.com/sonata-project/SonataPageBundle/pull/562.
## General

Inline scripts couldn't be cached and would pollute the html output.
## Security

There is also a [security bundle](https://github.com/nelmio/NelmioSecurityBundle#content-security-policy) which introduces some interesting information about security. You could completly disable inline script via a http header to reduce possible XSS attacks. 

For more information: http://www.w3.org/TR/CSP/
## Todo

The following files contains inline scripts and should be removed in the next major release, because this is a BC break.
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_history.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/form_admin_fields.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_list.html.twig

Refs https://github.com/sonata-project/SonataAdminBundle/issues/2911

**Comment by greg0ire** [comment]
Can you close duplicates of this?

**Comment by joshua-s** [comment]
Reserved!

**Comment by jordisala1991** [comment]
There is an orm linked issue containing more scripts that were moved from orm to admin

**Comment by fliespl** [comment]
How about to keep BC just utilize csp nonce functionality?

I.e. utilize <script nonce="{{ csp_nonce('script') }}"> from nelmio security bundle and fallback to own one?

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/issues/7158
