### ISSUE TITLE
Use twig blocks for form rendering

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4050]
We should replace all `<form>` elements in the twig templates with the twig function `form_start` and `form_end`. We should also move the `action` and `method` (POST, GET) attribute to the PHP files.

This would decouples the business logic from the layout.
## Todo

The following files contains form elements.
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/standard_layout.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/base_acl_macro.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/base_edit_form.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/base_list.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/batch_confirmation.html.twig
- [ ] https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/delete.html.twig
