### ISSUE TITLE
Symfony 5 - TODO list

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6365]
## This is TODO list require to add support for Symfony 5.

__Target branch:__ master (Sonata 4)
__Reason__:  To much huge BC-break in Sonata 3 (list below).

### Add support for Symfony 5.1 bundles ([bundles related to Symfony version](https://github.com/symfony/symfony/blob/master/composer.json#L40-L104)):
- [x] [symfony/asset](https://github.com/sonata-project/SonataAdminBundle/pull/6363)
- [x] [symfony/config](https://github.com/sonata-project/SonataAdminBundle/pull/6369)
- [ ] symfony/console
- [x] [symfony/dependency-injection](https://github.com/sonata-project/SonataAdminBundle/pull/6369)
- [ ] symfony/doctrine-bridge
- [ ] symfony/event-dispatcher
- [x] [symfony/form](https://github.com/sonata-project/SonataAdminBundle/pull/6362)
- [ ] symfony/framework-bundle
- [ ] symfony/http-kernel
- [x] [symfony/routing](https://github.com/sonata-project/SonataAdminBundle/pull/6369)
- [ ] symfony/security-bundle
- [ ] symfony/security-core
- [x] [symfony/security-csrf](https://github.com/sonata-project/SonataAdminBundle/pull/6363)
- [ ] [symfony/translation](https://github.com/sonata-project/SonataAdminBundle/pull/6373)
- [ ] symfony/twig-bridge
- [ ] symfony/twig-bundle

### Changes in self code:
- [ ] remove using `Symfony\Bundle\FrameworkBundle\Controller\Controller`
- [ ] remove using `Symfony\Bundle\FrameworkBundle\Controller\ControllerTrait`
- [x] add return type hint `Symfony\Component\OptionsResolver\OptionsResolver::getExtendedTypes(): iterable;`
- [ ] remove using `Symfony\Component\Translation\TranslatorInterface`

### Library:
- https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md
- https://github.com/symfony/symfony/blob/master/UPGRADE-5.1.md
- https://github.com/sonata-project/SonataAdminBundle/issues/5788
- https://github.com/sonata-project/SonataAdminBundle/pull/6093
- https://github.com/sonata-project/SonataAdminBundle/pull/6263

**Comment by wbloszyk** [comment]
Problem with TranslatorInterface we can resolve based on idea from comment:
https://github.com/sonata-project/SonataAdminBundle/pull/6342#discussion_r481826857

```php
namespace Symfony\Component\Translation;

if (!interface_exists('Symfony\Component\Translation\TranslatorInterface')) {
    /**
     * @deprecated since sonata-project/admin-bundle 3.x, to be removed in 4.0. Use \Symfony\Contracts\Translation\TranslatorInterface instead.
     */
    class_alias('Symfony\Contracts\Translation\TranslatorInterface', 'Symfony\Component\Translation\TranslatorInterface');
}
```

This alias will redirect ower `setTranslator(ComponentTranslatorInterface $translator)` to `setTranslator(ContractsTranslatorInterface $translator)` when user upgrade Symfony to 5. This will be BC.

**Comment by wbloszyk** [comment]
@sonata-project/contributors @dmaicher @jaikdean 
- WDYT? Can we add it in Sonata3?

If I miss any problem, feel free to add notes about it.
- Do you see more BC-break based on bundle list and Upgrade notes?

**Comment by dmaicher** [comment]
> Problem with TranslatorInterface we can resolve based on idea from comment:
> [#6342 (comment)](https://github.com/sonata-project/SonataAdminBundle/pull/6342#discussion_r481826857)
> 
> ```
> namespace Symfony\Component\Translation;
> 
> if (!interface_exists('Symfony\Component\Translation\TranslatorInterface')) {
>     /**
>      * @deprecated since sonata-project/admin-bundle 3.x, to be removed in 4.0. Use \Symfony\Contracts\Translation\TranslatorInterface instead.
>      */
>     class_alias('Symfony\Contracts\Translation\TranslatorInterface', 'Symfony\Component\Translation\TranslatorInterface');
> }
> ```
> 
> This alias will redirect ower `setTranslator(ComponentTranslatorInterface $translator)` to `setTranslator(ContractsTranslatorInterface $translator)` when user upgrade Symfony to 5. This will be BC.

Imho we should not do this. We don't own that interface so we should not alias it. This can cause all kind of weird issues with other bundles/libraries that do things based on the existence of the legacy interface etc.

**Comment by VincentLanglet** [comment]
> @sonata-project/contributors @dmaicher @jaikdean
> 
> * WDYT? Can we add it in Sonata3?

If it was easy, and didn't require BC-break, it would be ok. But it's not.
As explained in another discussion, I think we should focus on 4.0 to release it this year with the Symfony 5 support.

**Comment by wbloszyk** [comment]
@VincentLanglet I create project based on admin and symfony 5. In issue description I add next problem to resolve which can not be done without huge BC-break on Sonata 3. I will add this issue to https://github.com/sonata-project/SonataAdminBundle/milestone/7

**Comment by dmaicher** [comment]
@greg0ire @wbloszyk @VincentLanglet so was there a decision if we want to support Symfony 5.1 on 3.x or not? I'm slightly confused by all the comments on different issues and PRs :yum: 

Also seeing that we keep adding support for symfony 5.1 components on 3.x like in https://github.com/sonata-project/SonataAdminBundle/pull/6363

Out of interest: For how long would 3.x still be maintained (features, bug fixes) after 4.0 was released?

**Comment by VincentLanglet** [comment]
> @greg0ire @wbloszyk @VincentLanglet so was there a decision if we want to support Symfony 5.1 on 3.x or not? I'm slightly confused by all the comments on different issues and PRs 😋

It will certainly be on 4.0 rather than 3.x to avoid multiple BC-break.


> Also seeing that we keep adding support for symfony 5.1 components on 3.x like in #6363

This was an easy change, with no BC-break and adding no complexity to the code.

> Out of interest: For how long would 3.x still be maintained (features, bug fixes) after 4.0 was released?

Feature won't be added to 3.x as soon as we release 4.0 (except if does help our/the developer migration)
Bug could be backport to 3.x during some time, since the 4.0 introduce big changes. But keep in mind generally don't support multiple versions at the same time.

**Comment by wbloszyk** [comment]
> > Out of interest: For how long would 3.x still be maintained (features, bug fixes) after 4.0 was released?
> 
> Feature won't be added to 3.x as soon as we release 4.0 (except if does help our/the developer migration)
> Bug could be backport to 3.x during some time, since the 4.0 introduce big changes. But keep in mind generally don't support multiple versions at the same time.

I think we can support 3.x with some feature until we don't release whole Sonata4. Anyway we don't wanna do it for all PRs.

**Comment by eerison** [comment]
Well, I'm not sure if it's easy or not, But I'd like to help, I'll try to get this one `symfony/console`, But if you have some other suggestion to start could be good, because I'll see how it works :)

**Comment by VincentLanglet** [comment]
> Well, I'm not sure if it's easy or not, But I'd like to help, I'll try to get this one `symfony/console`, But if you have some other suggestion to start could be good, because I'll see how it works :)

Hi @eerison 
I think that everything will be solved by this PR: https://github.com/sonata-project/SonataAdminBundle/pull/6476
If you can help on it, it's perfect.

Otherwise you can help with some other Sonata4 PR like this issue https://github.com/sonata-project/SonataAdminBundle/issues/6404 ; since the symfony 5 compatibility will be only released with Sonata 4.

**Comment by jordisala1991** [comment]
I think this can be closed tol

**Comment by dmaicher** [comment]
I see a lot of things are happening on 3.x and master :muscle: :blush: 

Is there a todo list to see whats missing for releasing 4.0?

https://github.com/sonata-project/SonataAdminBundle/milestone/6 maybe ?

I'm really looking forward to a release with Symfony 5 support and would like to help if possible

**Comment by VincentLanglet** [comment]
> Is there a todo list to see whats missing for releasing 4.0?
> 
> https://github.com/sonata-project/SonataAdminBundle/milestone/6 maybe ?

Indeed, I try to keep the milestone up to date.
There is a lot of PR opened currently (and ready) but we're missing from maintainers time to review all of these (It's not the best period for github activity ^^). You may help with reviews/approval to catch errors faster.

The only missing issues are
- https://github.com/sonata-project/SonataAdminBundle/issues/6710 (Need discussion)
- https://github.com/sonata-project/SonataAdminBundle/issues/5806 (follow our will to clean the API)
- https://github.com/sonata-project/SonataAdminBundle/issues/6272 (follow our will to clean the API)
- https://github.com/sonata-project/SonataAdminBundle/issues/6260 (Need discussion)
We can't consider that it's a blocking point for 4.0 but it would be nice to have them.
