### ISSUE TITLE
Add param and return type hint

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6404]
I didn't find an issue to track the progress. We should add typehint every where on master.

### ToDo

- [x] Action
- [x] Admin => https://github.com/sonata-project/SonataAdminBundle/pull/6539
- [x] Block
- [x] Bridge
- [x] Builder
- [x] Command => https://github.com/sonata-project/SonataAdminBundle/pull/6407
- [x] Controller => https://github.com/sonata-project/SonataAdminBundle/pull/6537
- [x] Datagrid => https://github.com/sonata-project/SonataAdminBundle/pull/6562
- [x] DependencyInjection => https://github.com/sonata-project/SonataAdminBundle/pull/6495
- [x] Event => https://github.com/sonata-project/SonataAdminBundle/pull/6506
- [x] EventListener
- [x] Exception
- [x] Filter
- [x] Form
- [x] Guesser => https://github.com/sonata-project/SonataAdminBundle/pull/6526
- [x] Maker
- [x] Manipulator
- [x] Mapper
- [x] Menu
- [x] Model
- [x] Object
- [x] Route => https://github.com/sonata-project/SonataAdminBundle/pull/6465
- [x] Search => https://github.com/sonata-project/SonataAdminBundle/pull/6490
- [x] Security => https://github.com/sonata-project/SonataAdminBundle/pull/6521
- [x] Show
- [x] Templating => https://github.com/sonata-project/SonataAdminBundle/pull/6484
- [x] Translator => https://github.com/sonata-project/SonataAdminBundle/pull/6487
- [x] Twig => https://github.com/sonata-project/SonataAdminBundle/pull/6489
- [x] Util => https://github.com/sonata-project/SonataAdminBundle/pull/6366

**Comment by napestershine** [comment]
Is this list updated ?

**Comment by VincentLanglet** [comment]
@napestershine It is now.

There are some WIP PR: 
Command: https://github.com/sonata-project/SonataAdminBundle/pull/6407
Util: https://github.com/sonata-project/SonataAdminBundle/pull/6366
Admin: https://github.com/sonata-project/SonataAdminBundle/pull/6282
Form + Mapper: https://github.com/sonata-project/SonataAdminBundle/pull/6267

For Datagrid folder, I would say it's ok but there is the following TODO. (Which need a deprecation on 3.x)
```
    /**
     * TODO: allow only int to be set
     * Sets the maximum number of results per page.
     *
     * @param int|string $max
     */
    public function setMaxPerPage($max): void;

    /**
     * TODO: allow only int to be set
     * Sets the current page.
     *
     * @param int|string $page
     */
    public function setPage($page): void;
```

DependencyInjection, Event, Guesser, Maker, Menu, Route, Search, Templating, Translator, Twig are not finished

Model is almost done, we just need to discuss about some param like `@param mixed $id` that we may restrict to `int|string`.

For Security folder, AdminPermissionMap extends PermissionMapInterface so we can't add param typehint but I think return typehint are allowed.

**Comment by napestershine** [comment]
Thanks for the update.

**Comment by eerison** [comment]
Ok @VincentLanglet I'll take a look this one `Route`.

**Comment by VincentLanglet** [comment]
@eerison I think Route is started : https://github.com/sonata-project/SonataAdminBundle/pull/6465

**Comment by eerison** [comment]
@VincentLanglet what didn't start yet?

**Comment by VincentLanglet** [comment]
> @VincentLanglet what didn't start yet?

I would say everything except
- Admin
- Command
- Util
- Form
- Mapper
- Route
- I would not recommend Controller currently.

**Comment by eerison** [comment]
I'll see this `Util` on the weekend :) 

> > @VincentLanglet what didn't start yet?
> 
> I would say everything except
> 
>     * Admin
> 
>     * Command
> 
>     * Util
> 
>     * Form
> 
>     * Mapper
> 
>     * Route
> 
>     * I would not recommend Controller currently.

**Comment by VincentLanglet** [comment]
> I'll see this `Util` on the weekend :)

You maybe misunderstood. I listed the folder started, and Util is started: https://github.com/sonata-project/SonataAdminBundle/pull/6366

I already listed some WIP PR: https://github.com/sonata-project/SonataAdminBundle/issues/6404#issuecomment-703238750

But you can still work on Util if you want, and start from the @jordisala1991.
He opened multiple draft, and already said to me that anybody can take his work and finish it.

**Comment by tambait** [comment]
Hi,

- There was a phpdoc block for `LabelTranslatorStrategyInterface` which was removed by php-cs-fix after I added types for method arguments. Is this ok or phpdoc block should be returned? 

- I didn't put type hint method parameter for the `$resource` in `AdminExtractor` since it's not present in `ExtractorInterface` definition

- Initally I added return type hint for `extract` and `setPrefix` method but then removed them since they are not existing in `ExtractorInterface` definition

- There's a check failure/fatal error on `AdminExtractor.php#L121` about wrong type, but as far as I see 'ExtractorInterface' in 5.x has type `string` in `setPrefix` method (unlike 4.x)

Thanks.

**Comment by tambait** [comment]
I looked through files in Model directory and seems that all files have type hints set (except method parameters and return which are mixed, those have phpStan descriptions in PHPDoc blocks)

**Comment by VincentLanglet** [comment]
> I looked through files in Model directory and seems that all files have type hints set (except where method parameters and return value are mixed, those have phpStan descriptions in PHPDoc blocks)

Indeed

**Comment by VincentLanglet** [comment]
BTW @tambait, I think you can finish @jordisala1991 PR if you want ;)

**Comment by tambait** [comment]
> BTW @tambait, I think you can finish @jordisala1991 PR if you want ;)

Yes. I wanted to ask if I could help with some of the PR which in progress :)

**Comment by jordisala1991** [comment]
Yes, you can take over of my 2 Prs. Thank you for your time!

**Comment by tambait** [comment]
What's best way to do that? Should I fork your branch and then push commits to it?

**Comment by jordisala1991** [comment]
You can try cherry picking my commits and create a new Pr or start over. Otherwise I could be a blocker for this
